### ISSUE TITLE
Question about the database

### ISSUE THREAD

**Issue by iUseYahoo** [micfun123/Simplex_bot#17]
I see that the database already has stored data in it. I'm not sure if you meant for it to have data already in it but just wanting to let you know.

**Comment by micfun123** [comment]
Hey, thank you for the message.  I know of this I was not expecting the bot to grow in popularity so quickly. The data there was a backup from a few months ago. We are in the process of making new backups that are private and cleaning up GitHub. For more info and announcements please join the discord server.

https://discord.gg/ZYGygsPm5V
